// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmW_mMfTHXEXxOxaFZm_3xR_C_LRo8k8M',
    appId: '1:933474056744:android:2febccf49d107ab2f8131d',
    messagingSenderId: '933474056744',
    projectId: 'manitoxpress-cf855',
    databaseURL: 'https://manitoxpress-cf855-default-rtdb.firebaseio.com',
    storageBucket: 'manitoxpress-cf855.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClDKoO7XH88zCg8HIj0_zbPbvC_oNB8tU',
    appId: '1:933474056744:ios:a7f5f13e727b5020f8131d',
    messagingSenderId: '933474056744',
    projectId: 'manitoxpress-cf855',
    databaseURL: 'https://manitoxpress-cf855-default-rtdb.firebaseio.com',
    storageBucket: 'manitoxpress-cf855.appspot.com',
    androidClientId: '933474056744-5m32u4i8ltf1r975qbghcfe7slh6fmop.apps.googleusercontent.com',
    iosClientId: '933474056744-3cvqejt96s2mpdoijcg6g7ifiocu7kr7.apps.googleusercontent.com',
    iosBundleId: 'com.example.socio',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSp5RbLBZKMLHT0RJH3Zk5JRXZ4LOrQYc',
    appId: '1:933474056744:ios:a4f52d1b000b05bcf8131d',
    messagingSenderId: '933474056744',
    projectId: 'manitoxpress-cf855',
    databaseURL: 'https://manitoxpress-cf855-default-rtdb.firebaseio.com',
    storageBucket: 'manitoxpress-cf855.appspot.com',
    androidClientId: '933474056744-5m32u4i8ltf1r975qbghcfe7slh6fmop.apps.googleusercontent.com',
    iosClientId: '933474056744-dd50i7ubuoto1krkvavre1fjse1fe4v3.apps.googleusercontent.com',
    iosBundleId: 'com.xpress.manitosocio',
  );

}